CREATE TABLE IF NOT EXISTS `admin` (
  `IDADMIN` int(20) NOT NULL AUTO_INCREMENT,
  `MAILADMIN` varchar(255) NOT NULL,
  PRIMARY KEY (`IDADMIN`)
)

CREATE TABLE IF NOT EXISTS `parcours` (
  `IDPARCOURS` int(20) NOT NULL AUTO_INCREMENT,
  `NOMPARCOURS` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `IDRESPO` varchar(255) NOT NULL,
  `IDTEMOIGNAGE` varchar(20) NOT NULL,
  PRIMARY KEY (`IDPARCOURS`)
)

CREATE TABLE IF NOT EXISTS `respo` (
  `IDRESPO` int(20) NOT NULL AUTO_INCREMENT,
  `NOMRESPO` varchar(255) NOT NULL,
  `PRENOMRESPO` varchar(255) NOT NULL,
  `MAILRESPO` varchar(255) NOT NULL,
  `IDPARCOURS` int(20) NOT NULL,
  PRIMARY KEY (`IDRESPO`)
)

CREATE TABLE IF NOT EXISTS `temoignage` (
  `IDTEM` int(20) NOT NULL AUTO_INCREMENT,
  `NOMTEM` varchar(255) NOT NULL,
  `DESCRIPTEM` varchar(255) NOT NULL,
  `IDELEVE` int(20) NOT NULL,
  PRIMARY KEY (`IDTEM`)
)

CREATE TABLE IF NOT EXISTS `universite` (
  `IDUNIV` int(20) NOT NULL AUTO_INCREMENT,
  `NOMUNIV` varchar(255) NOT NULL,
  `DESCRIPUNIV` varchar(255) NOT NULL,
  `LIENUNIV` int(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS `etudiant` (
  `IDELEVE` bigint(20) NOT NULL AUTO_INCREMENT,
  `NUMELEVE` int(5) NOT NULL,
  `NOMELEVE` varchar(255) NOT NULL,
  `PRENOMELEVE` varchar(255) NOT NULL,
  `ETAPEELEVE` varchar(255) NOT NULL,
  `PROMOELEVE` int(4) NOT NULL,
  `MAILELEVE` varchar(255) NOT NULL,
  `MDPELEVE` varchar(255) NOT NULL,
  `IDPARCOURS` int(20) NOT NULL,
  PRIMARY KEY (`IDELEVE`)
)