CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `login` varchar(255) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  `nom` varchar(255) NOT NULL DEFAULT '',
  `nomFamille` varchar(255) NOT NULL DEFAULT '',
  `prenom` varchar(255) NOT NULL DEFAULT '',
  `type` varchar(255) NOT NULL DEFAULT '',
  `numero` varchar(255) NOT NULL DEFAULT '',
  `mail` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `parcours` (
  `IDPARCOURS` int(20) NOT NULL AUTO_INCREMENT,
  `NOMPARCOURS` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `IDRESPO` varchar(255) NOT NULL,
  `IDTEMOIGNAGE` varchar(20) NOT NULL,
  PRIMARY KEY (`IDPARCOURS`)
)

CREATE TABLE IF NOT EXISTS `temoignage` (
  `IDTEM` int(20) NOT NULL AUTO_INCREMENT,
  `NOMTEM` varchar(255) NOT NULL,
  `DESCRIPTEM` varchar(255) NOT NULL,
  `IDELEVE` int(20) NOT NULL,
  PRIMARY KEY (`IDTEM`)
)

CREATE TABLE IF NOT EXISTS `universite` (
  `IDUNIV` int(20) NOT NULL AUTO_INCREMENT,
  `NOMUNIV` varchar(255) NOT NULL,
  `DESCRIPUNIV` varchar(255) NOT NULL,
  `LIENUNIV` varchar(255) NOT NULL
  PRIMARY KEY (`IDUNIV`)
)